name: Test
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  unit-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run Vitest tests
        run: npx vitest
  integration-tests:
    needs: unit-tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start server
        run: npm run dev &
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  test-summary:
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: test-summary/action@v2.3
        with:
          paths: "./playwright-report/results.json"
          output: test-summary.md
        if: always()
      - uses: actions/upload-artifact@v4.3.1
        with:
          name: test-summary
          path: test-summary.md
        if: always()
